<!DOCTYPE html>
<html>
<head lang="en">
    <link rel="stylesheet" href="sources/css/main.css?<?php echo time(); ?>" />
    <!-- CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <!--This is the CDN to connect with BootstrapCDN CSS-->
    <!-- JS AND JQUERY -->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>    <meta charset="UTF-8">
    <!-- CDN FOR ICONS CART -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- CDN JS FUNCTIONS -->
    <script src="sources/js/functions.js?<?php echo time(); ?>"></script>
    <title>SCRIPTURES</title>
</head>
<body class="margin">
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
    <a class="navbar-brand" href="#">SCRIPTURES</a>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="#"> <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"></a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#"></a>
            </li>
        </ul>
        <form method="post" action="<?php echo htmlspecialchars('index.php?operation=detail'); ?>" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search Book" aria-label="Search">
            <button class="btn btn-warning text-white my-2 my-sm-0" type="submit" title="Search scripture">
                <a class="fa fa-search" id="amountTotal">
                </a>
            </button>
        </form>
        &nbsp;
        <button class="btn btn-warning text-white my-2 my-sm-0" type="button" title="Add scripture" data-toggle="modal" data-target="#modalscripture">
            <a class="fa fa-plus-square">
            </a>
        </button>
    </div>
</nav>
<!-- Modal -->
<div class="modal fade" id="modalscripture" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">NEW SCRIPTURE</h4>
                <button type="button" class="close" data-dismiss="modal">Go to Scriptures</button>
            </div>
            <div class="modal-body">
                <form method="post" action="<?php echo htmlspecialchars("index.php?operation=addscripture"); ?>">
                    Book:<br>
                    <input name="book" type="text" class="form-control" placeholder="Book">
                    Chapter:<br>
                    <input name="chapter" type="text" class="form-control" placeholder="Chapter">
                    Verse:<br>
                    <input name="verse" type="text" class="form-control" placeholder="Verse">
                    Content:<br>
                    <textarea name="content" id="note" rows="5" class="form-control" placeholder="Content"></textarea>
                    Topic:<br>
                    <?php
                    $data=$script->returnTopics();
                    foreach($data as $dat) {
                        ?>
                        <?php echo "<label for='".$dat["id"]."' class='cursor'>".$dat["name"].": "; ?><input type="checkbox" name="topics[]" id="<?php echo $dat["id"]; ?>" value="<?php echo $dat["id"]; ?>"></label>
                    <?php
                    }
                    ?>
                    <label for='other' class='cursor'>Other: <input type="checkbox" onclick="othertopics()" name="other" id="other" value="other"></label>
                    <input name="othertopic" id="othertopic" type="text" class="form-control display" style="display: none" placeholder="Other topic">
                    <br>
                    <button type="submit" class="btn btn-info form-control">ADD SCRIPTURE</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<h1><strong>Scriptures resources</strong></h1>
<div class="box-body">
    <div class="box-group" id="accordion">
        <div class="panel box box-primary">
            <div id="div1" class="div box-header with-border border border-primary ">
            <?php
            $data=$script->showScriptures("");

            foreach($data as $dat) {
                $i = 0;
                ?>
                <div>
                    <div class="box-body">
                        <?php echo "<strong>".$dat['book']." ".$dat['chapter'].":".$dat['verse'].' - </strong>"'.$dat['content'].'"<br>'; ?>
                        <strong>Topics:</strong>
                        <?php
                        $topics=$script->showTopics($dat['id']);
                        foreach($topics as $top) {
                            $i++;
                            echo "<br>Topic ".$i.": ".$top['name'];
                        }
                        ?>
                        <br><br>
                    </div>
                </div>
                <?php
            }
            ?>
            </div>
        </div>
    </div>
</div>
</body>
</html>